title = "Developing Innovative Therapies to Treat and Cure Viral Diseases | Antios Therapeutics"
baseURL = "/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]



# main menu
  [[menu.header]]
    weight = 3
    name = "Science"
    url = "/science"
	hasChildren = true
	  [[menu.header]]
	  parent = "Science"
	  name = "Overview"
	  URL = "/science"

	  [[menu.header]]
	  parent = "Science"
	  name = "Publications"
	  URL = "/publications"
	  
	  [[menu.header]]
	  parent = "Science"
	  name = "Hepatitis B Virus"
	  URL = "/hepatitis-b-virus"
	  
	  [[menu.header]]
	  parent = "Science"
	  name = "Hepatitis Delta Virus"
	  URL = "/hepatitis-delta-virus"
	  
  [[menu.header]]
    weight = 2
    name = "About"
    url = "/about"
	hasChildren = true
	  [[menu.header]]
	    weight = 1
		parent = "About"
		name = "Leadership"
		url = "/leadership"
	  [[menu.header]]
	    weight = 2
		parent = "About"
		name = "Board of Directors"
		url = "/board-of-directors"	
	  [[menu.header]]
	    weight = 3
		parent = "About"
		name = "Scientific Advisors"
		url = "/scientific-advisors"
	  [[menu.header]]
	    weight = 4
		parent = "About"
		name = "Investors"
		url = "/investors"
	
  [[menu.header]]
    weight = 4
    name = "News"
    url = "/news"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"


  
  #[[menu.footer]]
  #  weight = 5
  #  name = "Terms"
  #  url = "#"
	
  [[menu.science]]
    weight = 1
    name = "Overview"
    url = "/science"
  [[menu.science]]
    weight = 2
    name = "Publications"
    url = "/publications"
  [[menu.science]]
    weight = 3
    name = "Hepatitis B Virus"
    url = "/hepatitis-b-virus"
  [[menu.science]]
    weight = 4
    name = "Hepatitis Delta Virus"
    url = "/hepatitis-delta-virus"
	
  [[menu.about]]
    weight = 1
    name = "Leadership"
    url = "/leadership"
  [[menu.about]]
    weight = 2
    name = "Board of Directors"
    url = "/board-of-directors"	
  [[menu.about]]
    weight = 3
    name = "Scientific Advisors"
    url = "/scientific-advisors"
  [[menu.about]]
    weight = 4
    name = "Investors"
    url = "/investors"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# date_format = "2.1.2006"
  date_format = "Monday, Jan 2, 2006" 

  home = "Home"

  [params.slider]
    enable = true
    title = "Antios' mission is to develop innovative therapies to treat and cure Hepatitis B Virus (HBV) and other viral diseases"
   # subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Antios Therapeutics is a clinical-stage biopharmaceutical company focused on the development of innovative therapies to treat and cure viral diseases. Our lead therapeutic candidate, ATI-2173, is a first-in-class Active Site Polymerase Inhibitor Nucleotide (ASPIN) that is in development as the backbone of an oral, once-daily potential curative therapy for HBV."
   # paragraph = "Our team has decades of experience developing life changing therapies and technologies to treat and cure viral diseases."

  [params.blog]
    enable = true
    title = "News"
    subtitle = ""
	
  [params.feature]
    enable = true
    title = "HBV: A GLOBAL HEALTH CHALLENGE"
    content = "HBV is a virus of the liver transmitted through contact with blood or other body fluids of an infected individual. An estimated 1 out of 3 people have been infected worldwide. Many have no symptoms and either recover or develop chronic liver disease."
    contentSec = "Approximately 5% of those with acute HBV develop chronic HBV (over 250 million individuals worldwide), leading to scarring of the liver, liver cancer, and can be fatal if left untreated, with approximately 900,000 deaths per year (greater than HCV and HIV combined). Fewer than 25% of diagnosed carriers in the U.S. are under care, and fewer than 20% of those under care are on treatment. The HBV burden is even greater in China, with an estimated 90-100 million chronically infected individuals."
	contentThird = "While current treatments prevent progression of liver disease by reducing viral replication, only 5 - 10% of those chronically infected can be cured, meaning that most patients require lifelong treatment to control their infection."
	titleHead = "ATI-2173: A POTENTIAL SOLUTION"
	contentSubTwo = "Combining ATI-2173 with a nucleoside analogue in a once-a-day regimen could completely shut down HBV polymerase activity and viral replication, potentially curing HBV infected individuals. "
	# [params.feature.button]
    #  caption = "View Works"
    #  url = "#"


  # [params.call]
  #  enable = true
  #  title = "We design delightful digital experiences."
  #  paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Contact Us"
	
   # subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact"
     # address = "North Main Street, Brooklyn Australia"
      email = "info@antiostherapeutics.com"
	  email2 = "pr@antiostherapeutics.com"
     # phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "Locations"
	  
   