title = "Antios Therapeutics"
baseURL = "https://antios-therapeutics.netlify.com/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Science"
    url = "/science"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 4
    name = "News"
    url = "/news"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"
  
  [[menu.footer]]
    weight = 1
    name = "Science"
    url = "/science"
  [[menu.footer]]
    weight = 2
    name = "About"
    url = "/about"
  [[menu.footer]]
    weight = 3
    name = "News"
    url = "/news"
  [[menu.footer]]
    weight = 4
    name = "Contact"
    url = "/contact"
  #[[menu.footer]]
  #  weight = 5
  #  name = "Terms"
  #  url = "#"
	
  [[menu.science]]
    weight = 1
    name = "Overview"
    url = "#"
  [[menu.science]]
    weight = 2
    name = "Publications"
    url = "#"
	
  [[menu.about]]
    weight = 1
    name = "Leadership"
    url = "/leadership"
  [[menu.about]]
    weight = 2
    name = "Board of Directors"
    url = "/board-of-directors"	
  [[menu.about]]
    weight = 3
    name = "Scientific Advisors"
    url = "#"
  [[menu.about]]
    weight = 4
    name = "Investors"
    url = "/investors"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# date_format = "2.1.2006"
  date_format = "Monday, Jan 2, 2006" 

  home = "Home"

  [params.slider]
    enable = true
    title = "Antios' mission is to develop innovative therapies to treat and cure viral diseases"
   # subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "With our experienced team and lead oral candidate (ATI-2173), we are aiming to develop a cure for chronic hepatitis B."
   # paragraph = "Our team has decades of experience developing life changing therapies and technologies to treat and cure viral diseases."

  [params.blog]
    enable = true
    title = "News"
    subtitle = ""
	
  [params.feature]
    enable = true
    title = "A GLOBAL EPIDEMIC"
    content = "Hepatitis B (HBV) is a virus of the liver transmitted through contact with blood or other body fluids of an infected individual. An astounding 1 out of 3 people have been infected worldwide. Many have no symptoms and either recover or develop silent chronic liver disease; however, some develop acute illness with fatigue, poor appetite and jaundice."
    contentSec = "Approximately 5% of those with acute HBV develop chronic infection (over 250 million individuals worldwide), leading to scarring of the liver and later liver cancer, if not treated. With current treatment, only 5 - 10% of those chronically infected can be cured, meaning that most patients require lifelong treatment to control their infection."
	contentThird = "At Antios, we are committed to curing this global health epidemic."
	# [params.feature.button]
    #  caption = "View Works"
    #  url = "#"


  #[params.call]
   # enable = false
  #  title = "We design delightful digital experiences."
  #  paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Contact Us"
	
   # subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact"
     # address = "North Main Street, Brooklyn Australia"
      email = "info@antiostherapeutics.com"
	  email2 = "pr@antiostherapeutics.com"
     # phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "Locations"
	  
   