title = "Antios Therapeutics"
baseURL = "https://antios-therapeutics.netlify.com/"
languageCode = "en-us"
theme = "airspace-hugo"

[menu]

  [[menu.header]]
    weight = 2
    name = "Science"
    url = "/science"
  [[menu.header]]
    weight = 3
    name = "About"
    url = "/about"
  [[menu.header]]
    weight = 4
    name = "News"
    url = "/news"
  [[menu.header]]
    weight = 5
    name = "Contact"
    url = "/contact"
  
  [[menu.footer]]
    weight = 1
    name = "About"
    url = "/about"
  [[menu.footer]]
    weight = 2
    name = "Contact us"
    url = "#"
  [[menu.footer]]
    weight = 3
    name = "How it works"
    url = "#"
  [[menu.footer]]
    weight = 4
    name = "Blog"
    url = "#"
  [[menu.footer]]
    weight = 5
    name = "Terms"
    url = "#"
	
  [[menu.science]]
    weight = 1
    name = "Overview"
    url = "#"
  [[menu.science]]
    weight = 2
    name = "Publications"
    url = "#"
	
  [[menu.about]]
    weight = 1
    name = "Leadership"
    url = "#"
  [[menu.about]]
    weight = 2
    name = "Board of Directors"
    url = "# "	
  [[menu.about]]
    weight = 3
    name = "Scientific Advisors"
    url = "#"
  [[menu.about]]
    weight = 4
    name = "Investors"
    url = "/investors"

# The site's parameters
[params]

  # If you want to remove the copyright text you need a Themefisher license.
  # This license is offered with a 50% discount for all Hugo users.
  # For information see https://github.com/gohugoio/hugoThemes/issues/260

# date_format = "2.1.2006"
  date_format = "Monday, Jan 2, 2006" 

  home = "Home"

  [params.slider]
    enable = true
    title = "Antios' mission is to develop innovative therapies to treat and cure viral diseases."
   # subtitle = "We love the Web and the work we do.<br/>We work closely with our clients to deliver the best possible solutions for their needs"

  [params.wrapper]
    enable = true
    title = "About Us"
    italic = "Antios Therapeutics' mission is to develop innovative medicines to treat and cure viral diseases. With our lead oral candidate (ATI-2173) we are aiming to develop a cure for chronic Hepatitis B, a major global health epidemic affecting hundreds of millions of individuals worldwide."
    paragraph = "From early progress with HIV drugs to the development of the first cure for Hepatitis C, our team has decades of experience in developing life changing therapies."

  [params.blog]
    enable = true
    title = "News"
    subtitle = ""

  [params.feature]
    enable = true
    title = "A GLOBAL EPIDEMIC"
    content = "Hepatitis B (HBV) is a virus of the liver that has infected an astounding 1 out of 3 people worldwide. Of the nearly 30 million individuals infected annually, many have no symptoms and either recover or develop silent chronic liver disease; however, some develop acute illness with fatigue, poor appetite and jaundice (yellow eyes and skin).  Approximately 5% of those with acute hepatitis B develop chronic infection (over 250 million currently infected worldwide), leading to scarring of the liver and later liver cancer, if not treated. The common means of transmission in many parts of the world is from an HBV-infected mother to her child. With current treatment, only 5 - 10% of those chronically infected can be cured, meaning that most patients require lifelong treatment to control their infection. At Antios, we are committed to curing this global epidemic."
    # [params.feature.button]
    #  caption = "View Works"
    #  url = "#"


  #[params.call]
   # enable = false
  #  title = "We design delightful digital experiences."
  #  paragraph = "Read more about what we do and our philosophy of design. Judge for yourself The work and results we’ve achieved for other clients, and meet our highly experienced Team who just love to design."

  [params.contact]
    enable = true
    title = "Contact Us"
   # subtitle = "Don’t just take our word for it. Check out some of our latest work."
    [params.contact.form]
      name = "Your name"
      email = "Your email"
      subject = "Your subject"
      message = "Your message"
      button = "Send message"
    [params.contact.box]
      title = "Contact"
     # address = "North Main Street, Brooklyn Australia"
      email = "Information: info@antiostherapuetics.com"
	  email2 = "Public Relations: pr@antiostherapeutics.com"
     # phone = "Phone: +88 01672 506 744"
    [params.contact.gmaps]
      title = "Locations"
	  
   